import bcrypt from "bcryptjs";
import { db } from "./pool.js";

async function seed() {
  const client = await db.connect();

  try {
    await client.query("BEGIN");

    await client.query(`
      DELETE FROM submissions;
      DELETE FROM widgets;
      DELETE FROM users;
      DELETE FROM tenants;
    `);

    const tenantAResult = await client.query(
      `
      INSERT INTO tenants (name)
      VALUES ($1)
      RETURNING id, name
      `,
      ["Alpha Company"]
    );

    const tenantBResult = await client.query(
      `
      INSERT INTO tenants (name)
      VALUES ($1)
      RETURNING id, name
      `,
      ["Beta Company"]
    );

    const tenantA = tenantAResult.rows[0];
    const tenantB = tenantBResult.rows[0];

    const passwordHashA = await bcrypt.hash("Password123!", 12);
    const passwordHashB = await bcrypt.hash("Password123!", 12);

    await client.query(
      `
      INSERT INTO users (
        tenant_id,
        email,
        password_hash
      )
      VALUES ($1, $2, $3)
      `,
      [
        tenantA.id,
        "owner-a@example.com",
        passwordHashA,
      ]
    );

    const demoWidgetId =
      "11111111-1111-4111-8111-111111111111";

    await client.query(
      `
      INSERT INTO widgets (
        id,
        tenant_id,
        type,
        title,
        description,
        button_text,
        fields,
        display_options
      )
      VALUES ($1, $2, 'contact', $3, $4, $5, $6::jsonb, $7::jsonb)
      `,
      [
        demoWidgetId,
        tenantA.id,
        "Contact the FlyRank Demo Team",
        "This widget and its leads are generated by the repeatable demo seed.",
        "Send message",
        JSON.stringify([
          {
            name: "name",
            label: "Name",
            type: "text",
            required: true,
          },
          {
            name: "email",
            label: "Email",
            type: "email",
            required: true,
          },
          {
            name: "message",
            label: "Message",
            type: "textarea",
            required: false,
          },
        ]),
        JSON.stringify({ theme: "light" }),
      ]
    );

    await client.query(
      `
      INSERT INTO submissions (
        widget_id,
        tenant_id,
        payload,
        country,
        city,
        user_agent,
        created_at
      )
      VALUES
        ($1, $2, $3::jsonb, 'Pakistan', 'Karachi', 'demo-seed', NOW() - INTERVAL '2 days'),
        ($1, $2, $4::jsonb, 'United Kingdom', 'London', 'demo-seed', NOW() - INTERVAL '1 day'),
        ($1, $2, $5::jsonb, NULL, NULL, 'demo-seed', NOW() - INTERVAL '2 hours')
      `,
      [
        demoWidgetId,
        tenantA.id,
        JSON.stringify({ name: "Ayesha", email: "ayesha@example.com" }),
        JSON.stringify({ name: "Oliver", email: "oliver@example.com" }),
        JSON.stringify({ name: "No Geo Lead", email: "nogeo@example.com" }),
      ]
    );

    await client.query(
      `
      INSERT INTO users (
        tenant_id,
        email,
        password_hash
      )
      VALUES ($1, $2, $3)
      `,
      [
        tenantB.id,
        "owner-b@example.com",
        passwordHashB,
      ]
    );

    await client.query("COMMIT");

    console.log("Seed completed.");
    console.log("Tenant A login: owner-a@example.com");
    console.log("Tenant B login: owner-b@example.com");
    console.log("Password: Password123!");
    console.log(`Demo widget: ${demoWidgetId}`);
  } catch (error) {
    await client.query("ROLLBACK");
    console.error("Seed failed:", error);
    process.exitCode = 1;
  } finally {
    client.release();
    await db.end();
  }
}

seed();
